repos:
  - repo: local
    hooks:
      - id: update-requirements
        name: Update requirements.txt
        entry: bash -c 'pipenv requirements --dev > requirements.txt && git add requirements.txt'
        language: system
        files: ^(Pipfile|Pipfile.lock)$

      - id: alembic-check
        name: Alembic Check
        entry: pipenv run alembic check
        language: system
        pass_filenames: false
        stages: [pre-commit]