auth:
  access_token_expire_minutes: 30
  algorithm: HS256
  domain: localhost
  ldap_base_dn: dc=example,dc=com
  scopes:
    admin: admin
    student: student
    teacher: teacher
  secret_key: CHANGE_ME
