auth:
  access_token_expire_minutes: 30
  algorithm: HS256
  domain: dc.next.dev
  ldap_base_dn: DC=NEXT,DC=dev
  scopes:
    admin: admin
    student: student
    teacher: teacher
  secret_key: fcd67c9b07b2d022a3cff8570a1f48b0e73d78abefe3156aa6fde53afacf0210
